apiVersion: v1
kind: Service
metadata:
  name: hello-go
  labels:
    app: hello-go
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  selector:
    app: hello-go
